### ISSUE TITLE
Fix a place where invalid input terminates the server

### ISSUE THREAD

**Issue by tisztamo** [tisztamo/Junior#25]
## Project Description

Hey, Contributor!

Interpret issues freely. Need help or have ideas? Comment right here. Remember, this is the only forum where Krisztián answers questions - your golden ticket to help!

Keep it friendly, that's our vibe.

Happy contributing!

**Comment by DarshanDixit05** [comment]
Hey @tisztamo, I really want to know the exact meaning of "place" in the issue. Validating input and terminating the server is what I got. Can you please describe the issue briefly? Or the steps to recreate it ?

**Comment by tisztamo** [comment]
Hi @DarshanDixit05!

Thanks for asking, this really needs clarification!

A place I know about is the shebang check in  [src/execute/executeAndForwardOutput.js](https://github.com/tisztamo/Junior/blob/24a61c90a5a27115830b4bfb8e18607b5c07f886/src/execute/executeAndForwardOutput.js#L7)

The error should be catched in the corresponding handler and directed to the frontend instead of terminating the server. A console.log on the frontend (and on the backend) would be great for now.

**Comment by DarshanDixit05** [comment]
The error is now cached in the catch block and getting logged in the console. Please have a look at the picture. Let me know if its ok.
<img width="960" alt="Screenshot 2023-07-29 212151" src="https://github.com/tisztamo/Junior/assets/76871537/5745baad-bd4d-4dcf-ab41-c3f09aa62fb3">

**Comment by tisztamo** [comment]
Great, definitelly a solution to the original problem! Send a PR, please!

**Comment by DarshanDixit05** [comment]
Sure, I raised one.

**Comment by tisztamo** [comment]
#28 Closes this
