### ISSUE TITLE
clean install gives: npm ERR! notarget No matching version found for docsify-cli@^4.4.7.

### ISSUE THREAD

**Issue by pbharrin** [tisztamo/Junior#35]
A clean install gives me the following error: 
`npm ERR! notarget No matching version found for docsify-cli@^4.4.7.`

Running npm view docsify-cli versions
returns 
`[
  '0.1.0', '0.2.1',  '0.2.2',  '1.0.0',  '1.1.0',
  '1.1.1', '1.2.0',  '1.2.1',  '1.3.0',  '1.4.0',
  '1.5.0', '1.5.1',  '2.0.0',  '2.1.0',  '3.0.0',
  '3.0.1', '3.0.2',  '3.1.0',  '3.1.1',  '3.2.0',
  '3.2.1', '3.2.2',  '3.2.3',  '3.2.4',  '3.2.5',
  '3.3.0', '3.3.1',  '3.3.2',  '4.0.0',  '4.0.1',
  '4.0.2', '4.1.0',  '4.1.1',  '4.1.2',  '4.1.3',
  '4.1.4', '4.1.5',  '4.1.6',  '4.1.7',  '4.1.8',
  '4.1.9', '4.1.10', '4.1.11', '4.1.12', '4.2.0',
  '4.2.1', '4.3.0',  '4.4.0',  '4.4.1',  '4.4.2',
  '4.4.3', '4.4.4'
]`

No version 4.4.7 has been published.

**Comment by pbharrin** [comment]
I also looked into the source of docsify-cli and could not find a 4.4.7.

**Comment by tisztamo** [comment]
Uh, it was added today, I will check it soon but currently on mobile. Try to go back a few commits please!

**Comment by tisztamo** [comment]
Found the cause here:
 https://chat.openai.com/share/937d8682-300c-4e1f-84e5-607425cc4b21

I asked gpt both to install docsify-cli and also to edit package.json by heredocing the full file, in the same script. So it guessed the version in order to not loose the newly installed dep.
